workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mrtcnozvlk2@gmail.com